### ISSUE TITLE
presence at ViewSource Nov 2-4

### ISSUE THREAD

**Issue by daviddias** [websound/WebSound#1]
For those of you watching these repo, thank you! You definitely validated our thoughts and dreams to make the Web Platform the Universal Instrument, where people will be able to play and collaborate in music. @obensource will be pushing a full description of this project during the weekend, keep posted for the news!

@obensource and @thealphanerd will be present [ViewSource Nov 2-4 at Portland, OR](https://viewsourceconf.org/), if you are attending, make sure to say `Hi` and learn more about `WebSound`.

**Comment by MylesBorins** [comment]
woot!

**Comment by obensource** [comment]
@TheAlphaNerd can't wait!

**Comment by MylesBorins** [comment]
Closing... time has passed
