### ISSUE TITLE
WebSound Project Description Review

### ISSUE THREAD

**Issue by obensource** [websound/WebSound#2]
Please feel free to give constructive criticism and feedback for the WebSound project description. The [README](https://github.com/websound/WebSound/blob/master/README.md) is only the product of 2 individuals, let us know what we're missing.

**Comment by max-mapper** [comment]
some quick feedback
- linking to https://blog.andyet.com/2014/02/26/Pete-Seeger-lessons-learned-from-a-hard-link-to-the-old-world right off the bat is kind of a big ask of the reader, maybe supply an inline definition of 'death of peoples music' as a tl;dr
- whereas MIDI and DSP are pretty well known outside of music people, i am unsure if DAW is as universal, you might wanna define that
- I think before getting into Tools it would be nice to have a section to define what the goals are. so first you establish what the problems and goals are, then describe the proposed tools that address the problems to reach the goals

**Comment by obensource** [comment]
@maxogden +1 great feedback.
